---
extends:
  - standard
  - plugin:import/recommended
  - plugin:import/typescript # this line does the trick
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

# or configure manually:
plugins:
  - import
  - promise
  - "@typescript-eslint"

parser: "@typescript-eslint/parser"

parserOptions:
  sourceType: module
  ecmaVersion: 6

rules:
  comma-dangle: off
  "import/order": "error"
  "no-unused-vars": "off"
  "@typescript-eslint/no-unused-vars": ["error"]
  "@typescript-eslint/semi": "error"
  "@typescript-eslint/ban-ts-comment": "off"
  "semi": "off"
  "curly": "warn"
  "eqeqeq": "warn"
  "no-throw-literal": "warn"
  "space-before-function-paren": "off"
